### ISSUE TITLE
Не работает эвристика

### ISSUE THREAD

**Issue by kstrizhov** [Hailskurt/XPO-Logistics-test#2]
https://github.com/Hailskurt/XPO-Logistics-test/blob/577052e912e0f9a1c472c755af201b77da89c1db/main.py#L8

Если задать H = 0, выдает ошибку. при H=1 уходит в бесконечное выполнение. По факту должен делать перебор вершин, т.к. для всех чайлдов оценка одинаковая.

**Comment by Hailskurt** [comment]
> https://github.com/Hailskurt/XPO-Logistics-test/blob/577052e912e0f9a1c472c755af201b77da89c1db/main.py#L8
> 
> Если задать H = 0, выдает ошибку. при H=1 уходит в бесконечное выполнение. По факту должен делать перебор вершин, т.к. для всех чайлдов оценка одинаковая.

Поправил, это было связанно с тем что я использовал значение H для остановки основного цикла
